name: Complex

on : push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: date
  windows: windows-latest
    runs-on: 
    steps:
    - run: date
  macos:
    runs-on: macos-latest
    steps:
    - run: date
  depend:
    needs: [ubuntu,windoes,macos]
    runs-on: mavos-latest
    steps:
    - run: date
